ALTER TABLE "Business"
ADD COLUMN "gstNumber" TEXT,
ADD COLUMN "address" TEXT;

ALTER TABLE "Sale"
ADD COLUMN "reminderDate" TIMESTAMP(3);

ALTER TABLE "Product"
ADD COLUMN "costPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
