import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  shell: {
    alignSelf: "center",
    gap: 12,
    maxWidth: 460,
    width: "100%",
  },
  logo: {
    alignSelf: "center",
    height: 44,
    width: 136,
  },
  modeRow: {
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 14,
    flexDirection: "row",
    gap: 8,
    padding: 6,
    width: "100%",
  },
  modeButton: {
    alignItems: "center",
    borderRadius: 10,
    flex: 1,
    paddingVertical: 11,
  },
  modeButtonActive: {
    backgroundColor: "#ffffff",
  },
  modeButtonText: {
    color: "#4b5563",
    fontSize: 14,
    fontWeight: "700",
  },
  modeButtonTextActive: {
    color: "#111827",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    overflow: "hidden",
    paddingBottom: 20,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 10,
  },
  heroPanel: {
    height: 208,
  },
  heroImage: {
    resizeMode: "cover",
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  formHeader: {
    gap: 6,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  formTitle: {
    color: "#1f2937",
    fontSize: 32,
    fontWeight: "800",
  },
  formSubtitle: {
    color: "#6b7280",
    fontSize: 15,
    lineHeight: 21,
  },
  form: {
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  field: {
    gap: 6,
  },
  label: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "600",
  },
  inputShell: {
    alignItems: "center",
    borderColor: "#d1d5db",
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 12,
  },
  leadingIconWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: 18,
  },
  input: {
    color: "#111827",
    flex: 1,
    fontSize: 15,
    paddingVertical: 11,
  },
  trailingText: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "600",
  },
  inlineRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 2,
  },
  rememberRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  checkboxPressable: {
    paddingVertical: 2,
  },
  checkbox: {
    alignItems: "center",
    borderColor: "#d1d5db",
    borderRadius: 4,
    borderWidth: 1,
    height: 18,
    justifyContent: "center",
    width: 18,
  },
  checkboxActive: {
    backgroundColor: "#2563eb",
    borderColor: "#2563eb",
  },
  checkboxBlueActive: {
    backgroundColor: "#2563eb",
    borderColor: "#2563eb",
  },
  checkboxTick: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 11,
  },
  rememberText: {
    color: "#374151",
    fontSize: 13,
  },
  loginLinkText: {
    color: "#000000",
    fontSize: 13,
    fontWeight: "600",
  },
  signUpLinkText: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "600",
  },
  termsRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    marginTop: 2,
  },
  termsText: {
    color: "#374151",
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#000000",
    borderRadius: 10,
    paddingVertical: 13,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  signUpButton: {
    alignItems: "center",
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 14,
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 5,
  },
  signUpButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#000000",
    borderRadius: 10,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  disabledButton: {
    opacity: 0.6,
  },
  dividerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  divider: {
    backgroundColor: "#d1d5db",
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: "#6b7280",
    fontSize: 12,
  },
  googleButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1d5db",
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginHorizontal: 20,
    marginTop: 16,
    paddingVertical: 13,
    shadowColor: "#111827",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  googleIcon: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 999,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  googleButtonText: {
    color: "#374151",
    fontSize: 15,
    fontWeight: "500",
  },
  footerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  helperText: {
    color: "#6b7280",
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 20,
    paddingTop: 12,
    textAlign: "center",
  },
  footerText: {
    color: "#4b5563",
    fontSize: 14,
  },
  footerLink: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "700",
  },
  errorBox: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
    borderRadius: 10,
    borderWidth: 1,
    marginHorizontal: 20,
    marginTop: 18,
    padding: 12,
  },
  errorText: {
    color: "#dc2626",
    fontSize: 13,
    lineHeight: 18,
  },
  noticeBox: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
    borderRadius: 10,
    borderWidth: 1,
    marginHorizontal: 20,
    marginTop: 18,
    padding: 12,
  },
  noticeTitle: {
    color: "#1d4ed8",
    fontSize: 14,
    fontWeight: "700",
  },
  noticeBody: {
    color: "#1e40af",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  loadingScreen: {
    alignItems: "center",
    backgroundColor: "#eef2ff",
    flex: 1,
    gap: 12,
    justifyContent: "center",
    padding: 24,
  },
  loadingLogo: {
    height: 48,
    width: 140,
  },
  loadingText: {
    color: "#374151",
    fontSize: 15,
    fontWeight: "600",
  },
  dashboardScreen: {
    backgroundColor: "#eef2ff",
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  dashboardCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    gap: 16,
    padding: 22,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 8,
  },
  dashboardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dashboardLogo: {
    height: 34,
    width: 110,
  },
  dashboardBadge: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "700",
  },
  dashboardTitle: {
    color: "#111827",
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 32,
  },
  dashboardSubtitle: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 22,
  },
  dashboardMeta: {
    borderColor: "#e5e7eb",
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
  },
  infoRow: {
    borderBottomColor: "#e5e7eb",
    borderBottomWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  infoLabel: {
    color: "#6b7280",
    fontSize: 12,
    marginBottom: 3,
  },
  infoValue: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "600",
  },
});
